[database]
host = ""
username = ""
password = ""
database = ""

[smtp]
server = ""
port = 25
username = ""
password = ""
from = ""
to = []

[report]
send_time = "08:00"
setup_limit = 240

[general]
log_level = "INFO"
send_delay = 10